import json

with open('D:/CODING/AETHYXLabs/AethyxLM/colab_train_final.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Fix Cell 4 (index 3) - Tokenizer training: add nested dir fix and metadata generation
cell = nb['cells'][3]
new_source = [
    "# ============================================================\n",
    "# CELL 4: TRAIN BPE TOKENIZER (32k vocab) + SAVE TO DRIVE\n",
    "# ============================================================\n",
    "import subprocess, sys, shutil, os, time, json\n",
    "\n",
    "# Fix nested directory from git clone (repo clones to /content/AethyxLM/AethyxLM)\n",
    "nested = os.path.join(LOCAL_ROOT, 'AethyxLM')\n",
    "if os.path.exists(nested):\n",
    "    for item in os.listdir(nested):\n",
    "        src = os.path.join(nested, item)\n",
    "        dst = os.path.join(LOCAL_ROOT, item)\n",
    "        if os.path.exists(dst):\n",
    "            if os.path.isdir(dst):\n",
    "                shutil.rmtree(dst)\n",
    "            else:\n",
    "                os.remove(dst)\n",
    "        shutil.move(src, LOCAL_ROOT)\n",
    "    os.rmdir(nested)\n",
    "\n",
    "os.chdir(LOCAL_ROOT)\n",
    "sys.path.insert(0, LOCAL_ROOT)\n",
    "\n",
    "print('Training tokenizer...')\n",
    "result = subprocess.run(\n",
    "    [sys.executable, '-m', 'tokenizer.train_tokenizer'],\n",
    "    cwd=LOCAL_ROOT, capture_output=True, text=True\n",
    ")\n",
    "print(result.stdout)\n",
    "if result.returncode != 0:\n",
    "    print('STDERR:', result.stderr)\n",
    "    raise RuntimeError('Tokenizer training failed')\n",
    "\n",
    "# Verify\n",
    "sys.path.insert(0, LOCAL_ROOT)\n",
    "from tokenizer.tokenizer import AethyxTokenizer\n",
    "tok = AethyxTokenizer()\n",
    "print(f'[OK] Vocab size: {tok.vocab_size}')\n",
    "ids = tok.encode('Hello world')\n",
    "print(f'[OK] Encode: {ids}')\n",
    "print(f'[OK] Decode: {tok.decode(ids)}')\n",
    "\n",
    "# Robust Fix: If metadata.json was not created by the cloned train_tokenizer.py, generate it now!\n",
    "metadata_path = 'tokenizer/metadata.json'\n",
    "if not os.path.exists(metadata_path):\n",
    "    print('Creating missing metadata.json dynamically...')\n",
    "    corpus_path = 'tokenizer/data/corpus.txt'\n",
    "    metadata = {\n",
    "        'vocab_size': tok.vocab_size,\n",
    "        'tokenizer_type': 'BPE',\n",
    "        'special_tokens': ['<PAD>', '<UNK>', '<BOS>', '<EOS>'],\n",
    "        'normalizer': {\n",
    "            'type': 'Sequence',\n",
    "            'components': [\n",
    "                {'type': 'NFD'},\n",
    "                {'type': 'Lowercase'},\n",
    "                {'type': 'StripAccents'}\n",
    "            ]\n",
    "        },\n",
    "        'pre_tokenizer': {\n",
    "            'type': 'ByteLevel'\n",
    "        },\n",
    "        'trainer': {\n",
    "            'type': 'BpeTrainer',\n",
    "            'vocab_size': tok.vocab_size,\n",
    "            'min_frequency': 2,\n",
    "            'special_tokens': ['<PAD>', '<UNK>', '<BOS>', '<EOS>']\n",
    "        },\n",
    "        'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'),\n",
    "        'dataset_used': corpus_path,\n",
    "        'corpus_size_bytes': os.path.getsize(corpus_path) if os.path.exists(corpus_path) else 0,\n",
    "    }\n",
    "    with open(metadata_path, 'w', encoding='utf-8') as f:\n",
    "        json.dump(metadata, f, indent=2, ensure_ascii=False)\n",
    "\n",
    "# Copy tokenizer and metadata safely to Drive\n",
    "shutil.copy2('tokenizer/tokenizer.json', os.path.join(DRIVE_TOK, 'tokenizer.json'))\n",
    "if os.path.exists(metadata_path):\n",
    "    shutil.copy2(metadata_path, os.path.join(DRIVE_TOK, 'metadata.json'))\n",
    "print('[OK] Tokenizer and metadata saved to Drive')\n"
]
nb['cells'][3]['source'] = new_source

with open('D:/CODING/AETHYXLabs/AethyxLM/colab_train_final.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)

print("Fixed tokenizer cell with nested dir fix and metadata generation")