"""Shared filtering rules for streamed pretraining and tokenizer corpora."""

from __future__ import annotations

import re
import unicodedata
from collections.abc import Iterable, Mapping


SPACE_RE = re.compile(r"[ \t]+")
NEWLINE_RE = re.compile(r"\n{3,}")
SECRET_PATTERNS = (
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\bgh[pousr]_[A-Za-z0-9]{30,}\b"),
    re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b"),
)
GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated file",
    "automatically generated",
    "do not edit this file",
    "generated by the protocol buffer compiler",
)
REJECTED_PATH_PARTS = (
    "/node_modules/",
    "/vendor/",
    "/dist/",
    "/build/",
    "/target/",
    "/__pycache__/",
    "/third_party/",
    "/third-party/",
)
REJECTED_FILENAMES = (
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "composer.lock",
    "cargo.lock",
)


def normalize_text(text: str, preserve_formatting: bool = False) -> str:
    """Normalize Unicode without destroying indentation in source code."""
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\x00", " ")
    if preserve_formatting:
        return text.strip()
    text = SPACE_RE.sub(" ", text)
    return NEWLINE_RE.sub("\n\n", text).strip()


def matches_required_values(
    document: Mapping[str, object], required_values: Mapping[str, Iterable[object]]
) -> bool:
    for field, accepted in required_values.items():
        allowed = set(accepted)
        if document.get(field) not in allowed:
            return False
    return True


def is_high_quality_code(document: Mapping[str, object], text: str) -> bool:
    """Cheap conservative filters for public-repository source files."""
    path = "/" + str(document.get("path", "")).replace("\\", "/").lower().lstrip("/")
    filename = path.rsplit("/", 1)[-1]
    if any(part in path for part in REJECTED_PATH_PARTS):
        return False
    if filename in REJECTED_FILENAMES or ".min." in filename:
        return False

    prefix = text[:4096].lower()
    if any(marker in prefix for marker in GENERATED_MARKERS):
        return False
    if any(pattern.search(text) for pattern in SECRET_PATTERNS):
        return False

    lines = text.splitlines()
    if len(lines) < 3:
        return False
    nonempty = [line for line in lines if line.strip()]
    if len(nonempty) < 2:
        return False
    if max(map(len, lines), default=0) > 2_000:
        return False
    if sum(map(len, lines)) / max(1, len(lines)) > 180:
        return False

    alphanumeric = sum(character.isalnum() for character in text)
    if alphanumeric / max(1, len(text)) < 0.20:
        return False
    return True
